name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger workflow on tags starting with 'v'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install dependencies (Linux only)
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev

    # Step 3: Configure and build the project using CMake
    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -S .
      shell: bash

    - name: Build the project
      run: cmake --build build --config Release

    # Step 4: Package the built binary
    - name: Archive binary
      run: |
        mkdir -p release
        cp build/draw release/
      shell: bash

    # Step 5: Create a release
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}  # Use the tag that triggered the workflow
        release_name: Release ${{ github.ref_name }}
        body: |
          Automated release for ${{ github.ref_name }}.
        draft: false
        prerelease: false

    # Step 6: Upload release asset
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/draw  # Path to the binary
        asset_name: draw-linux
        asset_content_type: application/octet-stream
